### PUT update patient
PUT http://localhost:4000/patients/74d30f48-fd8c-4c9c-8834-928b721a3889
Content-Type: application/json

{
    "name": "Jonh Joe",
    "email": "testing@gmail.com",
    "address": "address",
    "dateOfBirth": "2005-06-08"
}